version: '3.9'

services:
  db:
    restart: always
    image: postgres:16
    container_name: eventa_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=db_dev_password
      - POSTGRES_USER=db_dev_user
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    container_name: eventa_user_service
    command: "/bin/sh /usr/src/app/start-dev.sh"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=db_dev_user
      - DB_PASSWORD=db_dev_password
      - DB_NAME=user_service
      - JWT_SECRET=secret_key_for_testing_purposes_only
      - JWT_EXPIRES_IN=1800
      - JWT_REFRESH_SECRET=refresh_secret_key_for_testing_purposes_only
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
