version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: user-service-postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_PASSWORD=db_dev_password
      - POSTGRES_USER=db_dev_user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service Application
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./start-dev.sh"]

volumes:
  postgres_data:
    driver: local

